services:
  pdf-extractor-jvm:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - TESSERACT_LANGUAGE=fin
      - TESSERACT_AUTO_DETECT_LANGUAGE=true
      - QUARKUS_LOG_LEVEL=INFO
    volumes:
      - ./uploads:/tmp/uploads:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pdf/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  pdf-extractor-native:
    build:
      context: .
      dockerfile: Dockerfile.native
    ports:
      - "8081:8080"
    environment:
      - TESSERACT_LANGUAGE=fin
      - TESSERACT_AUTO_DETECT_LANGUAGE=true
      - QUARKUS_LOG_LEVEL=INFO
    volumes:
      - ./uploads:/tmp/uploads:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pdf/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s